import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createPlan, verifyPlan, materializePlan, normalizeConfig, markdownReport } from '../dist/index.js';
const parent = path.resolve('.demo'); fs.mkdirSync(parent, { recursive: true });
const run = fs.mkdtempSync(path.join(parent, 'run-')), repo = path.join(run, 'repository'); fs.mkdirSync(repo);
const env = { ...process.env, GIT_AUTHOR_NAME: 'PR Slicer Demo', GIT_AUTHOR_EMAIL: 'demo@localhost', GIT_COMMITTER_NAME: 'PR Slicer Demo', GIT_COMMITTER_EMAIL: 'demo@localhost' };
const git = (...args) => execFileSync('git', ['-c', 'core.hooksPath=/dev/null', '-c', 'commit.gpgSign=false', '-C', repo, ...args], { env, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const write = (file, data) => { const target = path.join(repo, file); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, data); };
git('init', '-b', 'main'); git('config', 'core.autocrlf', 'false');
write('tsconfig.json', JSON.stringify({ compilerOptions: { strict: true, target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', types: [], skipLibCheck: true } }));
write('README.md', '# Session demo\n'); git('add', '.'); git('commit', '-m', 'Initial session project'); git('checkout', '-b', 'feature/session');
write('src/types.ts', 'export interface Session { id: string; expiresAt: number; }\n');
write('src/backend.ts', 'import type { Session } from "./types.js";\nexport function isExpired(session: Session, now: number) { return session.expiresAt <= now; }\n');
write('src/ui.ts', 'import { isExpired } from "./backend.js";\nimport type { Session } from "./types.js";\nexport function sessionLabel(session: Session, now: number) { return isExpired(session, now) ? "expired" : "active"; }\n');
git('add', '.'); git('commit', '-m', 'Add session expiration');
const plan = createPlan({ repo, base: 'main', head: 'feature/session', config: normalizeConfig({ limits: { targetChangedLines: 2, hardMaxChangedLines: 50 } }) });
fs.writeFileSync(path.join(run, 'plan.json'), JSON.stringify(plan, null, 2) + '\n');
const verified = await verifyPlan(plan, { semantic: true });
fs.writeFileSync(path.join(run, 'verified.json'), JSON.stringify(verified, null, 2) + '\n'); fs.writeFileSync(path.join(run, 'report.md'), markdownReport(verified));
if (verified.verification.status !== 'passed') throw new Error(JSON.stringify(verified.checks));
const result = materializePlan(verified, { prefix: 'slice/session' });
console.log(`Demo completata: ${run}\nGruppi: ${plan.groups.length}; verifica: ${verified.verification.level}\nBranch: ${result.branches.map(b => b.name).join(', ')}\nTree finale identico: ${result.finalTreeOid}`);
